// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB78WwoQ8-SSUw8UBxiuCh6PkrLgo5NlQ0',
    appId: '1:718731555921:web:2c4eaf109eee505154b470',
    messagingSenderId: '718731555921',
    projectId: 'armbot-apps',
    authDomain: 'armbot-apps.firebaseapp.com',
    storageBucket: 'armbot-apps.appspot.com',
    measurementId: 'G-4YMTGECK9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCraM8lBvKCrTLSPuQwmB58NJdUOoJgK7I',
    appId: '1:718731555921:android:98803a0f95639f6854b470',
    messagingSenderId: '718731555921',
    projectId: 'armbot-apps',
    storageBucket: 'armbot-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGoICcRn3pe0FWppsNx_cVqgdp3JMvrUQ',
    appId: '1:718731555921:ios:84f54829aa28573f54b470',
    messagingSenderId: '718731555921',
    projectId: 'armbot-apps',
    storageBucket: 'armbot-apps.appspot.com',
    iosClientId: '718731555921-44rndqbdqo7grsvmmmqqa4a19saavdil.apps.googleusercontent.com',
    iosBundleId: 'com.example.armHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGoICcRn3pe0FWppsNx_cVqgdp3JMvrUQ',
    appId: '1:718731555921:ios:84f54829aa28573f54b470',
    messagingSenderId: '718731555921',
    projectId: 'armbot-apps',
    storageBucket: 'armbot-apps.appspot.com',
    iosClientId: '718731555921-44rndqbdqo7grsvmmmqqa4a19saavdil.apps.googleusercontent.com',
    iosBundleId: 'com.example.armHealth',
  );
}
